### PR TITLE
Fixed possible failures when importing data

### PR DESCRIPTION
**Pull request by Bavragor**
This was necessary for me in order to get a full api key running.

### CODE REVIEW

**Comment by tarioch** [comment]
Thanks for this, could you have a look at the scrutinizer issue?

https://scrutinizer-ci.com/g/tarioch/eveapi-fetcher-bundle/inspections/0d8aded8-cc2d-4650-88d4-594cd824bbba/issues/files/Entity/CharWalletJournal.php?status=new&orderField=path&order=asc&honorSelectedPaths=0

**Comment by Bavragor** [comment]
Well the problem is, that taxReceiverID always should be an integer, but sometimes it occurs to be an empty string, so this is intended.

**Comment by tarioch** [comment]
Makes sense, you mind changing https://github.com/tarioch/eveapi-fetcher-bundle/blob/master/Component/EveApi/Char/WalletJournalUpdater.php instead of the entity? Should be cleaner and would avoid the problem. I prefer to deal with the API quirks in the api updaters instead of directly the entities.

**Comment by Bavragor** [comment]
Yes you are right. I applied the changes :)

**Pull request merged**
